### ISSUE TITLE
Get which points identify mouth and eyes.

### ISSUE THREAD

**Issue by Neogene** [kylemcdonald/FaceTracker#13]
The face tracking works really flawlessly but how can we detect which are the points that compose the eyes and the mouth? They are the ones inside the face shape perimeter but there is a way to get them precisely to define three polygons to create a mask (i'm trying to use the face  to create a mask to apply to a texture to avoid the texture cover the eyes and the mouth area). thanx in advance. The idea is to fill the face area without filling the eyes and mouth polygons to generate the mask to be applied to a texture centered to the nose of the human.

**Comment by mosspassion** [comment]
@Neogene How did you raise the eyelash points higher? I want a forehead mask too, and I'm trying to get ride of the eyes and mouth hole.
