### ISSUE TITLE
make in ubutu

### ISSUE THREAD

**Issue by yongjook** [kylemcdonald/FaceTracker#15]
Hi,

I'm having problem during the make step:
...
g++ -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  -c -o src/lib/Tracker.o src/lib/Tracker.cc -I/home/joon/Documents/Install-OpenCV-master/Ubuntu/2.4/OpenCV/opencv-2.4.8//include -Iinclude/
g++   -o bin/face_tracker src/lib/IO.o src/lib/PDM.o src/lib/Patch.o src/lib/CLM.o src/lib/FDet.o src/lib/PAW.o src/lib/FCheck.o src/lib/Tracker.o  -L/home/joon/Documents/Install-OpenCV-master/Ubuntu/2.4/OpenCV/opencv-2.4.8//build/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_objdetect
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: ld returned 1 exit status
make: *** [bin/face_tracker] Error 1

I think the path for libraries in makefile is incorrect.

# Paths
OPENCV_PATH=/home/joon/Documents/Install-OpenCV-master/Ubuntu/2.4/OpenCV/opencv-2.4.8/

# Programs
CC=
CXX=g++

# Flags
ARCH_FLAGS=
CFLAGS=-Wextra -Wall -pedantic-errors $(ARCH_FLAGS) -O3 -Wno-long-long
LDFLAGS=$(ARCH_FLAGS)
DEFINES=
INCLUDES=-I$(OPENCV_PATH)/include -Iinclude/
LIBRARIES=-L$(OPENCV_PATH)/build/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_objdetect

In LIBRARIES i set the path to OPENCV_PATH/build/lib since that's where opencv_core, highgui, imgpro and objdetect is location in .so form. But the file names are different in such that it is libopencv_core.so.2.4.8

should i change
LIBRARIES=-L$(OPENCV_PATH)/build/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_objdetect
to 
LIBRARIES=-L$(OPENCV_PATH)/build/lib -lopencv_core.so.2.4.8?

**Comment by kylemcdonald** [comment]
going to close this since i haven't heard of anyone else having problems compiling FaceTracker on ubuntu.

**Comment by zkandroid** [comment]
hello,I had the same problem:
          make: *** [bin/face_tracker] Error 1
that's because then OPENCV_PATH is not correct,it worked when i changed it in then Makefile
