### ISSUE TITLE
Can I get help with the 'round': identifier not found? It is the only error appearing apart from the conversion warnings.  Thanks.

### ISSUE THREAD

**Issue by wilfody** [kylemcdonald/FaceTracker#19]

**Comment by kylemcdonald** [comment]
are you using visual studio 2012? `round()` is not included.

http://stackoverflow.com/questions/21065537/where-are-round-rint-and-so-on-c-functions-in-visual-studio-2012

usually i add the function definition manually or use a different compiler.
