### ISSUE TITLE
Which is the deformable model approach used in "FaceTracker" implementation?

### ISSUE THREAD

**Issue by jovan-fernandes** [kylemcdonald/FaceTracker#20]
What differences between the implementation on the FaceTracker and the implementation described on "Mastering OpenCV with Practical Computer Vision Projects. PACKT, Oct 2012. " by Saragih's?
There is some paper describing it?

**Comment by ajdroid** [comment]
@jovanoasis , did you find the answer?

**Comment by jovanoasis** [comment]
I' understand that the version containing in the book is a simplified version made for explanation, that is the ASM without improvements. Saragih have one paper that describes some of this improvement, many of these are in Facetracker.
