### ISSUE TITLE
How to Install on windows.

### ISSUE THREAD

**Issue by asifbashir** [kylemcdonald/FaceTracker#22]
Hi,
I am new to openFrameworks and  I am trying to build FaceTracker and ofxFaceTracker on windows using codeBlocks. Can you please tell me the steps to built it on windows.

Thanks

**Comment by kylemcdonald** [comment]
if you would like to build FaceTracker on windows with openFrameworks, please use the https://github.com/kylemcdonald/ofxFaceTracker/ repository instead of this one, as it comes with project files prepared for you.
