### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by asifbashir** [kylemcdonald/FaceTracker#23]
Hi,
     I build FaceTracker on windows using CodeBloks, but it is giving me a segmentation fault. I debugged the program and found that segfault occur in PDM.cpp file at line 6.

1   void PDM::CalcShape3D(cv::Mat &s,cv::Mat &plocal)
2   {
3     assert((s.type() == CV_64F) && (plocal.type() == CV_64F));
4     assert((s.rows == _M.rows) && (s.cols = 1));
5     assert((plocal.rows == _E.cols) && (plocal.cols == 1));
6     s = _M + _V*plocal; return;
7     }

Can anybody help me.

Thanks

**Comment by kylemcdonald** [comment]
could you provide any more information about this bug?

have you tried building this project with the makefile instead of code::blocks? does that work, or not?

because this is an old issue i'm going to close it for now unless you or someone else reopens it.
