### ISSUE TITLE
Facial landmarks and triangulation for a single image

### ISSUE THREAD

**Issue by shinydinosaur** [kylemcdonald/FaceTracker#24]
Is there an entry-point function where I can get the facial landmarks and triangulation for a single image input instead of a video stream?

Thanks.

**Comment by kylemcdonald** [comment]
the main call to FaceTracker is demonstrated in this line https://github.com/kylemcdonald/FaceTracker/blob/master/src/exe/face_tracker.cc#L195

in the demo it does this repeatedly on incoming video images, but you can do this on a single image that you have loaded into an `cv::Mat`

**Comment by chr0x** [comment]
Kyle, do you know if there's any way to export these landmarks to a file? I'm using this input:

    cv::Mat img;
    cv::FileStorage file("landmarks.txt", cv::FileStorage::WRITE);
    img = cv::imread(argv[1], CV_LOAD_IMAGE_COLOR);
    cv::cvtColor(img,gray,CV_BGR2GRAY);
