### ISSUE TITLE
Retraining

### ISSUE THREAD

**Issue by akapusta** [kylemcdonald/FaceTracker#25]
I am trying to use FaceTracker to estimate the pose of a human subject's head for a wide variety of poses. 
I found that FaceTracker works better on certain people's heads than others, and does not not work for various head poses.
Is it possible to train the system on specific people or for certain poses? 
Running the executable does not appear to do anything, as far as I can tell. Or at least if I only give it inputs/options according to the help info. When running it in the command window it gives no errors, just give a new input line. I can get it to output the help info.
Do I need to use the openframeworks wrapper to be able to get anything from it?

**Comment by kylemcdonald** [comment]
unfortunately the training code for FaceTracker is not available, it belongs to the university jason developed it at. the best you can do is change the options on the tracker, and change the lighting conditions if you have control over them.
