### ISSUE TITLE
SegFault on tracker draw

### ISSUE THREAD

**Issue by pythonanonuser** [kylemcdonald/FaceTracker#27]
I'm using the python wrapper, and when I run any of the example programs, a segfault routinely occurs using the tracker.draw method. Any ideas on how to fix?

**Comment by kylemcdonald** [comment]
this might be an opencv/python issue. please make sure you can run an example using the camera input in python first, then try the facetracker.

**Comment by 12rohanb** [comment]
I've played around with commenting out lines. The camera input works fine. 

The line causing trouble is: 
img = tracker.draw(img, conns, trigs)

When I comment it out, it works. Otherwise, it doesn't.

**Comment by kylemcdonald** [comment]
can you please post:

- which OS you are using
- which version of python
- which version of opencv

and i'll see if i can recreate it. thanks!

**Comment by 12rohanb** [comment]
I'm using Mac OSX 10.10, Python 2.7, and opencv 2.4.8 (that's the one I installed via anaconda. I wasn't able to import facetracker if I compiled with the brew install, so I had to use this one.)
