### ISSUE TITLE
Android port

### ISSUE THREAD

**Issue by ajdroid** [kylemcdonald/FaceTracker#29]
Hey, not really a bug.
I've found your and Jason's work pretty handy, so I built an Android app over it. [Here](https://github.com/ajdroid/facetrackerapp) is a link to the repo. Standalone apk also available. Hoping you could include it in the readme so it can help others.

**Comment by kylemcdonald** [comment]
great! happy to add a link once the license.md is mirrored and a note about the license is added to the readme, like this:

> It is available free for non-commercial use, and may be redistributed under these conditions. Please see `license.md` for complete details. For commercial use, [request a quote](http://facetracker.net/quote/).

**Comment by ajdroid** [comment]
Done.

**Comment by kylemcdonald** [comment]
thanks!
