### ISSUE TITLE
Face substitution including the forehead

### ISSUE THREAD

**Issue by vertgo** [kylemcdonald/FaceTracker#32]
I want to try the face substitution but I need to include the forehead. In the tracker, I only see the mesh draw up until the eyebrows. What's the best way to solve this?

**Comment by aisgirish** [comment]
Have you found any solution? I have one.

**Comment by kylemcdonald** [comment]
sorry, for face substitution please add issues to the relevant repository.

but in general, i've had the best results doing face substitution without trying to replace the forehead. otherwise you have to deal with very difficult features like bangs.
