### ISSUE TITLE
c-api is outdated, small changes can be made to run with opencv3.0

### ISSUE THREAD

**Issue by xinario** [kylemcdonald/FaceTracker#33]
1.in face_tracker.cc 
line177:
changed to cv::VideoCapture camera(CV_CAP_ANY); if(!camera.isOpened()) return -1;

line188:
changed to camera.read(frame);

2.in io.h
replace <opencv/cv.h> with <opencv2/opencv.hpp>

3.in Makefile add link to -lopencv_videoio

and that's all.

I compiled it on my mac with opencv3.0 and g++5.3 and it works.

**Comment by kylemcdonald** [comment]
Thank you for your contribution!
