### ISSUE TITLE
Hi there is there a way to run this code in windows , visual studio 

### ISSUE THREAD

**Issue by AAAAldah** [kylemcdonald/FaceTracker#34]

**Comment by kylemcdonald** [comment]
http://mattgemmell.com/what-have-you-tried/

i don't run windows so i can't provide help (and no one else can either) unless you share some more info about what precisely isn't working.

**Comment by vcidst** [comment]
Hey, can this issue be opened again? I tried to see if the Makefile is nmake compatible but it doesn't look like that.

```
C:\Code\Github\FaceTracker>nmake

Microsoft (R) Program Maintenance Utility Version 14.16.27024.1
Copyright (C) Microsoft Corporation.  All rights reserved.

makefile(32) : fatal error U1000: syntax error : ')' missing in macro invocation
Stop.
```

If there are any CMake compatible (or nmake compatible) Makefiles available, that will be helpful!
