### ISSUE TITLE
coordinates 2d from an determined point

### ISSUE THREAD

**Issue by joaopbarbosa** [kylemcdonald/FaceTracker#35]
Hi everyone,
i'm trying to print the coordinates from a specific point of the mask. How can i make this and how can i define the same point that i will have the coordinates? I'm a beginner on this, so if you could help me, it will be really nice.

Thanks

**Comment by kylemcdonald** [comment]
it sounds like you might want to work at a higher level, try using openFrameworks and https://github.com/kylemcdonald/ofxFaceTracker
