### ISSUE TITLE
Explanation for tracking profile face

### ISSUE THREAD

**Issue by yuccai** [kylemcdonald/FaceTracker#40]
Hi,

Does anyone know how the program handle the tracking when the face rotate? When we rotate the head and when we show our left/right profile, the program only displays points of the half face shown.
There is a function 'int CLM::GetViewIdx()' which returns the index of the head orientation (0 for front face, 1 for left profile, 2 for right profile). This index is used to read an array '_visi' which states what patch belongs or not to each orientation. 
I've determined that this array is used to draw the points but I would like to know if it is also used for the tracking, if all patches are tracked but only the not hidden are displayed or if only the not hidden patches are tracked.
I know that something happens when my head orientation reaches a certain amount of yaw because there is a blip, little jumps between 2 drawings.

Thanks in advance for more explanations

**Comment by kylemcdonald** [comment]
Hi, thanks for your contribution. But it turns out this is more of a request for help rather than an issue/bug report, and I only have the time to maintain bugs. So I'm going to have to close this. Sorry!
