### ISSUE TITLE
/usr/local/lib/libopencv_core.so：对‘cudaEventRecord’未定义的引用

### ISSUE THREAD

**Issue by yja1** [kylemcdonald/FaceTracker#43]
when run make,the error like this: 
/usr/local/lib/libopencv_core.so：对‘cudaEventRecord’未定义的引用
/usr/local/lib/libopencv_core.so：对‘cudaEventRecord’未定义的引用
....
collect2: error: ld returned 1 exit status

**Comment by kylemcdonald** [comment]
This is a problem with your OpenCV build, not FaceTracker.
